services:
  elasticsearch:
    build:
      context: ./services/elk/elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    restart: unless-stopped
    expose:
      - ${ELASTICSEARCH_PORT}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      # - logger.level=error
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
    networks:
      - elk
      - vault
    labels:
      - "projectLabel=transcendence"

  logstash:
    build:
      context: ./services/elk/logstash
      dockerfile: Dockerfile
    container_name: logstash
    restart: unless-stopped
    expose:
      - ${LOGSTASH_PORT}
    volumes:
      - ./services/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ${LOGS_PATH}:${LOGS_DIR}:ro
    environment:
      - http.host=0.0.0.0
      - xpack.monitoring.elasticsearch.hosts=http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.username=${ELASTICSEARCH_USER}
      - ELASTICSEARCH_USER=${ELASTICSEARCH_USER}
    networks:
      - elk
      - vault
    labels:
      - "projectLabel=transcendence"

  kibana:
    build:
      context: ./services/elk/kibana
      dockerfile: Dockerfile
    container_name: kibana
    restart: unless-stopped
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    volumes:
      - ./services/elk/kibana/imports:/usr/share/kibana/imports
      - ./services/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      - KIBANA_OBJECTS_URL=${KIBANA_OBJECTS_URL}
      - KIBANA_STATUS_URL=${KIBANA_STATUS_URL}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USER=${ELASTICSEARCH_USER}
    networks:
      - elk
      - vault
    labels:
      - "projectLabel=transcendence"

volumes:
  elasticsearch-data:

networks:
  elk:
    name: elk_network
    driver: bridge
  vault:
    name: vault_network
    driver: bridge
    external: true