services:
  transcendence:
    build:
      context: .
    image: i_transcendence
    container_name: c_transcendence
    platform: linux/arm64
    volumes:
      - /Users/paco/sgoinfre/transcendence_paco/home:/home
    restart: unless-stopped
    tty: true
    stdin_open: true

